// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "Log a user in",
                "produces": [
                    "application/json"
                ],
                "summary": "Login User",
                "operationId": "login-user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email Address",
                        "name": "email",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "400": {
                        "description": "Invalid login data"
                    },
                    "401": {
                        "description": "Unauthorized user"
                    }
                }
            }
        },
        "/refresh-token": {
            "post": {
                "description": "Refresh token for re-authentication",
                "produces": [
                    "application/json"
                ],
                "summary": "Refresh a Token",
                "operationId": "refresh-token",
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "400": {
                        "description": "Token refresh failed"
                    },
                    "401": {
                        "description": "Unauthorized user"
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Create a new user",
                "produces": [
                    "application/json"
                ],
                "summary": "Create New User",
                "operationId": "create-user",
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "400": {
                        "description": "Invalid input format"
                    }
                }
            }
        },
        "/tickets": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "List all tickets available",
                "produces": [
                    "application/json"
                ],
                "summary": "Get All Tickets",
                "operationId": "get-tickets",
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "500": {
                        "description": "Database error"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a new ticket",
                "produces": [
                    "application/json"
                ],
                "summary": "Create New Ticket",
                "operationId": "create-ticket",
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "400": {
                        "description": "Bad request"
                    }
                }
            }
        },
        "/tickets/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get single ticket",
                "produces": [
                    "application/json"
                ],
                "summary": "Get a Ticket",
                "operationId": "get-ticket",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "400": {
                        "description": "Invalid ticket ID"
                    },
                    "500": {
                        "description": "Database error"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete single ticket",
                "produces": [
                    "application/json"
                ],
                "summary": "Delete a Ticket",
                "operationId": "delete-ticket",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "400": {
                        "description": "Invalid ticket ID"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update single ticket",
                "produces": [
                    "application/json"
                ],
                "summary": "Update a Ticket",
                "operationId": "update-ticket",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "400": {
                        "description": "Invalid ticket ID"
                    },
                    "404": {
                        "description": "Ticket not found"
                    },
                    "500": {
                        "description": "Database error"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "SJ Ticketing API Go F*ck Yourself",
	Description:      "8===D----",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
