// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "Log a user in",
                "produces": [
                    "application/json"
                ],
                "summary": "Login User",
                "operationId": "login-user",
                "parameters": [
                    {
                        "description": "User Login",
                        "name": "user_login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "400": {
                        "description": "Invalid login data"
                    },
                    "401": {
                        "description": "Unauthorized user"
                    }
                }
            }
        },
        "/refresh-token": {
            "post": {
                "description": "Refresh token for re-authentication",
                "produces": [
                    "application/json"
                ],
                "summary": "Refresh a Token",
                "operationId": "refresh-token",
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "400": {
                        "description": "Token refresh failed"
                    },
                    "401": {
                        "description": "Unauthorized user"
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Create a new user",
                "produces": [
                    "application/json"
                ],
                "summary": "Create New User",
                "operationId": "create-user",
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "400": {
                        "description": "Invalid input format"
                    }
                }
            }
        },
        "/tickets": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "List all tickets available",
                "produces": [
                    "application/json"
                ],
                "summary": "Get All Tickets",
                "operationId": "get-tickets",
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "500": {
                        "description": "Database error"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a new ticket",
                "produces": [
                    "application/json"
                ],
                "summary": "Create New Ticket",
                "operationId": "create-ticket",
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "400": {
                        "description": "Bad request"
                    }
                }
            }
        },
        "/tickets/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get single ticket",
                "produces": [
                    "application/json"
                ],
                "summary": "Get a Ticket",
                "operationId": "get-ticket",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "400": {
                        "description": "Invalid ticket ID"
                    },
                    "500": {
                        "description": "Database error"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete single ticket",
                "produces": [
                    "application/json"
                ],
                "summary": "Delete a Ticket",
                "operationId": "delete-ticket",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "400": {
                        "description": "Invalid ticket ID"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update single ticket",
                "produces": [
                    "application/json"
                ],
                "summary": "Update a Ticket",
                "operationId": "update-ticket",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "400": {
                        "description": "Invalid ticket ID"
                    },
                    "404": {
                        "description": "Ticket not found"
                    },
                    "500": {
                        "description": "Database error"
                    }
                }
            }
        },
        "/tickets/{id}/completed": {
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update ticket status to completed",
                "produces": [
                    "application/json"
                ],
                "summary": "Update a Ticket status to completed",
                "operationId": "update-ticket-completed",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "400": {
                        "description": "Invalid ticket ID"
                    },
                    "404": {
                        "description": "Ticket not found"
                    },
                    "500": {
                        "description": "Database error"
                    }
                }
            }
        },
        "/tickets/{id}/pending": {
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update ticket status to pending",
                "produces": [
                    "application/json"
                ],
                "summary": "Update a Ticket status to pending",
                "operationId": "update-ticket-pending",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "400": {
                        "description": "Invalid ticket ID"
                    },
                    "404": {
                        "description": "Ticket not found"
                    },
                    "500": {
                        "description": "Database error"
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Get Single User",
                "produces": [
                    "application/json"
                ],
                "summary": "Get Single User",
                "operationId": "get-user",
                "responses": {
                    "200": {
                        "description": "Successful response"
                    },
                    "400": {
                        "description": "Database error"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.UserLogin": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "192.168.1.57:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "SJ Ticketing API",
	Description:      "Ticketing API v1.0",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
